### ISSUE TITLE
Status code: 404

### ISSUE THREAD

**Issue by MalteKiefer** [rubemlrm/copr-packages#67]
Since today, I get this message:

```
Errors during downloading metadata for repository 'copr:copr.fedorainfracloud.org:rubemlrm:nordzy-icon':
  - Status code: 404 for https://download.copr.fedorainfracloud.org/results/rubemlrm/nordzy-icon/fedora-39-x86_64/repodata/repomd.xml (IP: 13.32.110.108)
Error: Failed to download metadata for repo 'copr:copr.fedorainfracloud.org:rubemlrm:nordzy-icon': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

```

**Comment by rubemlrm** [comment]
Hello @MalteKiefer

Thank you for your report, looks that was caused by a wrong configuration that I did on fedora copr website.
I've tried to install on a new PC and it was working.
Can you test from your side? Maybe you will need to force clean the packages cache, I had to do that step on a PC that had the repository already configured.

Cheers

**Comment by rubemlrm** [comment]
Issue closed, since i didn't get further feedback.
